# Generated by Django 5.2.7 on 2025-10-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="last_watered",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="species",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="water_frequency",
        ),
        migrations.AddField(
            model_name="plant",
            name="care_instructions",
            field=models.TextField(default="No care instructions provided."),
        ),
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(default="No description provided."),
        ),
        migrations.DeleteModel(
            name="UserRegistration",
        ),
    ]
