# Generated by Django 5.2.7 on 2025-10-04 12:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_remove_plant_added_by_remove_plant_last_watered_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="custom_interval",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If frequency is Custom, number of days between watering.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="last_watered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="water_frequency",
            field=models.CharField(
                choices=[
                    ("1", "Daily"),
                    ("2", "Every 2 days"),
                    ("3", "Every 3 days"),
                    ("7", "Weekly (every 7 days)"),
                    ("custom", "Custom (days)"),
                ],
                default="7",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="water_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name="plant",
            name="care_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("dob", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("course", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "scheduled_time"],
                "unique_together": {("plant", "scheduled_date", "scheduled_time")},
            },
        ),
    ]
